thrusters:
  back:
    f:
    - 0.0
    - 0.0
    - 1.0
    k_backward: -1.0
    k_forward: -1.0
    r:
    - -0.25
    - 0.0
    - 0.0
    thruster_number: 1
  front:
    f:
    - 0.0
    - 0.0
    - 1.0
    k_backward: -1.0
    k_forward: -1.0
    r:
    - 0.25
    - 0.0
    - 0.0
    thruster_number: 3
  left:
    f:
    - 1.0
    - 0.0
    - 0.0
    k_backward: -1.0
    k_forward: -1.0
    r:
    - 0.0
    - 0.2
    - 0.0
    thruster_number: 3
  right:
    f:
    - 1.0
    - 0.0
    - 0.0
    k_backward: -1.0
    k_forward: -1.0
    r:
    - 0.0
    - -0.2
    - 0.0
    thruster_number: 2
